### ISSUE TITLE
Suite release has undergone XA

### ISSUE THREAD

**Issue by izgeri** [cyberark/community#48]
### Open Source Users

|||
|---|---|
|_As a_|Conjur Open Source user|
|_I want_|to know what tools and integrations there are for Conjur|
|_so that_|I can evaluate whether Conjur is suitable for me to use, and which tools / integrations are compatible with my systems.|

|||
|---|---|
|_As a_|Conjur Open Source user|
|_I want_|to know what versions of Conjur OSS components to use|
|_so that_|I am using reliable, well-tested software that works together as expected when used within my systems.|

### OSS Suite Component Maintainers

|||
|---|---|
|_As a_|maintainer of a Conjur OSS suite component|
|_I want_|to know how to ensure new versions of my component get into the OSS suite release|
|_so that_|OSS users can benefit from new features my team is adding to our component.|

|||
|---|---|
|_As a_|maintainer of a Conjur OSS suite component|
|_I want_|to know what I'm responsible for testing and what will be tested in the OSS suite|
|_so that_|it's clear what tests I need to include and maintain in my component repository, and which tests belong in the central OSS suite release repo.|

|||
|---|---|
|_As a_|maintainer of a Conjur OSS suite component|
|_I want_|to know what standards I need to maintain in my repository|
|_so that_|my CHANGELOG entries, releases, READMEs, etc are compatible with the OSS suite release.|

### Conjur OSS Contributors

|||
|---|---|
|_As a_|Conjur Open Source contributor|
|_I want_|to know what components there are|
|_so that_|I can find components that I can contribute to.|

|||
|---|---|
|_As a_|Conjur Open Source contributor|
|_I want_|to know what is included in the Conjur OSS suite|
|_so that_|if there are tools or platforms that are not supported, I can make a difference by building something to fill the gap.|

### Conjur OSS Suite Release Managers

|||
|---|---|
|_As a_|Conjur release manager|
|_I want_|o know what changes have been made to components since the last suite release|
|_so that_|I can decide if enough changes have been made to merit a new release.|

|||
|---|---|
|_As a_|Conjur release manager|
|_I want_|to know how to create a new release, including any manual steps that are required|
|_so that_|I can successfully create a new release without missing any steps.|

|||
|---|---|
|_As a_|Conjur release manager|
|_I want_|to know the results of automated tests|
|_so that_|I can be sure all included components work together as expecteed at the pinned versions.|

### Conjur Core Downstream Developer
|||
|---|---|
|_As a_|developer on a downstream project that uses Conjur as its core|
|_I want_|to know when there are new Conjur OSS suite releases|
|_so that_|I can review the changes and update my project to use the latest OSS suite release version of Conjur.|

|||
|---|---|
|_As a_|developer on a downstream project that uses Conjur as its core|
|_I want_|a machine readable summary of what is included in each OSS suite release|
|_so that_|I can build automation around the OSS suite releases as needed.|

**Comment by izgeri** [comment]
@alexkalish wdyt about this card? I still have it open in the suite epic

**Comment by alexkalish** [comment]
Let's close it.  We need to move on to other projects and we'll stay attentive to feedback.
