### ISSUE TITLE
There is a file descriptors blog post

### ISSUE THREAD

**Issue by izgeri** [cyberark/community#58]
AC:
- [ ] The gist published here: https://gist.github.com/doodlesbykumbi/d2f3a90796e0f83792bb47f310da79ca
is edited based on the feedback already given and migrated to WordPress to be published on blogs.conjur.org

**Comment by doodlesbykumbi** [comment]
![image](https://user-images.githubusercontent.com/8653164/78798120-858c7080-79b0-11ea-93f3-f2eb06a67ee7.png)

Posting this here for free storage :)
