### ISSUE TITLE
All community team repos have a CODEOWNERS file

### ISSUE THREAD

**Issue by izgeri** [cyberark/community#60]
The following repos should have a CODEOWNERS file in `.github/CODEOWNERS` that includes the single line:
```
* @cyberark/community-and-integrations-team
```
- [ ] cyberark/community
- [ ] cyberark/conjur-oss-suite-release
- [ ] conjurdemos/cloudfoundry-conjur-demo
- [ ] conjurdemos/kubernetes-conjur-demo
- [ ] conjurdemos/pet-store-demo
- [ ] conjurinc/cloudfoundry-conjur-tile
- [ ] cyberark/ansible-conjur-host-identity
- [ ] cyberark/cloudfoundry-conjur-buildpack
- [ ] cyberark/conjur-puppet
- [ ] cyberark/conjur-service-broker
- [ ] cyberark/sidecar-injector
- [ ] cyberark/terraform-provider-conjur
- [ ] conjurinc/secretless-broker-e2e-tests
- [x] conjurinc/secretless-demo
- [ ] conjurinc/secretless-server
- [ ] cyberark/go-mssqldb
- [ ] cyberark/secretless-broker
- [ ] conjurinc/summon-conjurcli
- [ ] cyberark/summon
- [ ] cyberark/summon-aws-secrets
- [ ] cyberark/summon-chefapi
- [ ] cyberark/summon-conjur
- [ ] cyberark/summon-keyring
- [ ] cyberark/summon-s3

**Comment by JakeQuilty** [comment]
`secretes-demo` was the only one that I couldn't do, because it's archived
