### ISSUE TITLE
Every Conjur OSS repo has a pull request template

### ISSUE THREAD

**Issue by izgeri** [cyberark/community#68]
The following projects should be updated to have the same pull request template as the one used in Conjur, here: https://github.com/cyberark/conjur/blob/master/.github/PULL_REQUEST_TEMPLATE.md.
- [x] cyberark/ansible-conjur-collection
- [x] cyberark/conjur-authn-iam-client-python
- [x] cyberark/bash-lib
- [x] cyberark/conjur
- [x] cyberark/conjur-oss-helm-chart
- [x] cyberark/conjur-google-cloud-marketplace
- [x] cyberark/conjur-cli
- [x] cyberark/conjur-api-dotnet
- [x] cyberark/conjur-api-go
- [x] cyberark/conjur-api-java
- [x] cyberark/conjur-api-python3
- [x] cyberark/conjur-api-ruby
- [x] cyberark/conjur-authn-k8s-client
- [x] cyberark/conjur-google-cloud-marketplace
- [x] cyberark/conjur-oss-suite-release
- [x] cyberark/conjur-quickstart
- [x] cyberark/dev-flow
- [x] cyberark/secrets-provider-for-k8s
- [x] cyberark/conjur-service-broker
- [x] cyberark/cloudfoundry-conjur-buildpack
- [x] cyberark/ansible-conjur-host-identity
- [x] cyberark/conjur-credentials-plugin
- [x] cyberark/conjur-puppet
- [x] cyberark/kubernetes-conjur-deploy
- [x] cyberark/parse-a-changelog
- [x] cyberark/terraform-provider-conjur
- [x] cyberark/sidecar-injector
- [x] cyberark/slosilo
- [x] cyberark/summon
- [x] cyberark/summon-aws-secrets
- [x] cyberark/summon-chefapi
- [x] cyberark/summon-conjur
- [x] cyberark/summon-keyring
- [ ] cyberark/summon-s3

These repos already have a pull request template, please review them and determine whether they can be updated to a format like the Conjur template, or if they need to remain as-is:
- [x] cyberark/conjur
- [x] cyberark/conjur-template
- [x] cyberark/secretless-broker

**Comment by JakeQuilty** [comment]
These all should stay the same:
 `cyberark/conjur` -  Same as the one we are copying
 `cyberark/conjur-template` - Has repo specific template
 `cyberark/secretless-broker` - Has repo specific template

**Comment by JakeQuilty** [comment]
New PR link for `cyberark/summon-keyring`: https://github.com/cyberark/summon-keyring/pull/20
