### ISSUE TITLE
Every Conjur OSS repo has an updated SECURITY.md

### ISSUE THREAD

**Issue by izgeri** [cyberark/community#70]
The following projects should be updated to have the same SECURITY.md file as the template file, here: https://github.com/cyberark/conjur-template/blob/master/CONTRIBUTING.md.

Note that the following three lines should also be added to `.github/CODEOWNERS` in each of these projects (if no CODEOWNERS file already exists, then the conjur-template version can be copied entirely): https://github.com/cyberark/conjur-template/blob/master/.github/CODEOWNERS#L11-L13

- [ ] cyberark/ansible-conjur-collection
- [ ] cyberark/conjur-authn-iam-client-python
- [ ] cyberark/bash-lib
- [ ] cyberark/conjur
- [ ] cyberark/conjur-oss-helm-chart
- [ ] cyberark/conjur-google-cloud-marketplace
- [ ] cyberark/conjur-cli
- [ ] cyberark/conjur-api-dotnet
- [ ] cyberark/conjur-api-go
- [ ] cyberark/conjur-api-java
- [ ] cyberark/conjur-api-python3
- [ ] cyberark/conjur-api-ruby
- [ ] cyberark/conjur-authn-k8s-client
- [ ] cyberark/conjur-google-cloud-marketplace
- [ ] cyberark/conjur-oss-suite-release
- [ ] cyberark/conjur-quickstart
- [ ] cyberark/dev-flow
- [ ] cyberark/secrets-provider-for-k8s
- [ ] cyberark/conjur-service-broker
- [ ] cyberark/cloudfoundry-conjur-buildpack
- [ ] cyberark/ansible-conjur-host-identity
- [ ] cyberark/conjur-credentials-plugin
- [ ] cyberark/conjur-puppet
- [ ] cyberark/kubernetes-conjur-deploy
- [ ] cyberark/parse-a-changelog
- [ ] cyberark/terraform-provider-conjur
- [ ] cyberark/sidecar-injector
- [ ] cyberark/slosilo
- [ ] cyberark/summon
- [ ] cyberark/summon-aws-secrets
- [ ] cyberark/summon-chefapi
- [ ] cyberark/summon-conjur
- [ ] cyberark/summon-keyring
- [ ] cyberark/summon-s3
- [ ] cyberark/conjur
- [ ] cyberark/secretless-broker

**Comment by JakeQuilty** [comment]
Addressed round 1 of suggestions in the PRs.
